fastcat:
  target_loop_rate_hz:                100
  zero_latency_required:              True
  actuator_position_directory:        /tmp/
  actuator_fault_on_missing_pos_file: False

buses:  
  - type: offline_bus
    ifname: eth0
    enable_autorecovery: True

    devices:
    - device_class: Jed
      name: jed_1
      initial_cmd: 42
